# Generated by Django 5.2.12 on 2026-03-14

from django.db import migrations, models


class AddDatabaseIndexes(migrations.Migration):

    dependencies = [
        ('contents', '0002_initial'),
        ('media', '0007_media_reference_alter_media_file_and_more'),
        ('comments', '0003_initial'),
    ]

    operations = [
        # Content model indexes
        migrations.AddIndex(
            model_name='content',
            index_name='content_status_created_idx',
            fields=['status', '-created_at'],
        ),
        migrations.AddIndex(
            model_name='content',
            index_name='content_status_published_idx',
            fields=['status', '-published_at'],
        ),
        migrations.AddIndex(
            model_name='content',
            index_name='content_top_created_idx',
            fields=['-is_top', '-created_at'],
        ),
        migrations.AddIndex(
            model_name='content',
            index_name='content_slug_idx',
            fields=['slug'],
        ),
        migrations.AddIndex(
            model_name='content',
            index_name='content_author_status_idx',
            fields=['author', 'status'],
        ),
        # Media model indexes
        migrations.AddIndex(
            model_name='media',
            index_name='media_file_hash_idx',
            fields=['file_hash'],
        ),
        migrations.AddIndex(
            model_name='media',
            index_name='media_uploader_created_idx',
            fields=['uploader', '-created_at'],
        ),
        migrations.AddIndex(
            model_name='media',
            index_name='media_file_type_idx',
            fields=['file_type'],
        ),
        # Comment model indexes
        migrations.AddIndex(
            model_name='comment',
            index_name='comment_article_created_idx',
            fields=['article', '-created_at'],
        ),
        migrations.AddIndex(
            model_name='comment',
            index_name='comment_user_created_idx',
            fields=['user', '-created_at'],
        ),
        migrations.AddIndex(
            model_name='comment',
            index_name='comment_approved_created_idx',
            fields=['is_approved', '-created_at'],
        ),
        migrations.AddIndex(
            model_name='comment',
            index_name='comment_parent_idx',
            fields=['parent'],
        ),
        # CommentLike model index
        migrations.AddIndex(
            model_name='commentlike',
            index_name='comment_like_user_idx',
            fields=['user'],
        ),
    ]

