# Generated by Django 5.2.12 on 2026-03-28 11:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0003_category_updated_at"),
        ("contents", "0002_initial"),
        ("tags", "0003_tag_updated_at_alter_tag_slug"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="content",
            index=models.Index(
                fields=["status", "-created_at"], name="content_status_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="content",
            index=models.Index(
                fields=["status", "-published_at"], name="content_status_published_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="content",
            index=models.Index(
                fields=["-is_top", "-created_at"], name="content_top_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="content",
            index=models.Index(fields=["slug"], name="content_slug_idx"),
        ),
        migrations.AddIndex(
            model_name="content",
            index=models.Index(
                fields=["author", "status"], name="content_author_status_idx"
            ),
        ),
    ]
