# Generated by Django 5.2.12 on 2026-05-03 09:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_category_category_sort_created_idx_and_more'),
        ('contents', '0003_content_content_status_created_idx_and_more'),
        ('tags', '0004_tag_tag_created_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['category', 'status', '-created_at'], name='content_cat_stat_created_idx'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['status', '-view_count'], name='content_status_viewcount_idx'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['title'], name='content_title_idx'),
        ),
    ]
