# Generated by Django 4.2.7 on 2026-03-31 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import images.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="相册名称")),
                ("description", models.TextField(blank=True, verbose_name="相册描述")),
                (
                    "cover",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="album_covers/",
                        verbose_name="封面图片",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="是否公开"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="所属用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "相册",
                "verbose_name_plural": "相册",
                "db_table": "albums",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UploadChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("upload_id", models.CharField(max_length=64, verbose_name="上传ID")),
                ("chunk_number", models.IntegerField(verbose_name="分块序号")),
                ("chunk_size", models.IntegerField(verbose_name="分块大小")),
                ("total_chunks", models.IntegerField(verbose_name="总分块数")),
                ("total_size", models.BigIntegerField(verbose_name="文件总大小")),
                ("filename", models.CharField(max_length=255, verbose_name="文件名")),
                ("file_hash", models.CharField(max_length=64, verbose_name="文件哈希")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upload_chunks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="上传用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "上传分块",
                "verbose_name_plural": "上传分块",
                "db_table": "upload_chunks",
                "indexes": [
                    models.Index(
                        fields=["upload_id"], name="upload_chun_upload__7eb522_idx"
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="upload_chun_user_id_01b421_idx",
                    ),
                ],
                "unique_together": {("upload_id", "chunk_number")},
            },
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "file",
                    models.ImageField(
                        upload_to=images.models.image_upload_path,
                        verbose_name="图片文件",
                    ),
                ),
                (
                    "filename",
                    models.CharField(max_length=255, verbose_name="原始文件名"),
                ),
                ("file_size", models.BigIntegerField(verbose_name="文件大小(字节)")),
                (
                    "file_hash",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="文件哈希"
                    ),
                ),
                ("width", models.IntegerField(verbose_name="图片宽度")),
                ("height", models.IntegerField(verbose_name="图片高度")),
                ("format", models.CharField(max_length=10, verbose_name="图片格式")),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="图片标题"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="图片描述")),
                (
                    "tags",
                    models.JSONField(blank=True, default=list, verbose_name="标签"),
                ),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="是否公开"),
                ),
                (
                    "access_count",
                    models.IntegerField(default=0, verbose_name="访问次数"),
                ),
                (
                    "storage_backend",
                    models.CharField(
                        default="local", max_length=50, verbose_name="存储后端"
                    ),
                ),
                ("storage_path", models.TextField(verbose_name="存储路径")),
                (
                    "album",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="images",
                        to="images.album",
                        verbose_name="所属相册",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="所属用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "图片",
                "verbose_name_plural": "图片",
                "db_table": "images",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"], name="images_user_id_0c6cc6_idx"
                    ),
                    models.Index(
                        fields=["album", "-created_at"],
                        name="images_album_i_4d5dfa_idx",
                    ),
                    models.Index(
                        fields=["file_hash"], name="images_file_ha_ae0e36_idx"
                    ),
                    models.Index(
                        fields=["is_public"], name="images_is_publ_f615e6_idx"
                    ),
                ],
            },
        ),
    ]
