# Generated by Django 5.2.12 on 2026-04-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_init_default_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
