# Generated by Django 6.0.4 on 2026-04-21 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roles", "0002_init_default_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="permission",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
    ]
