# Generated by Django 5.2.12 on 2026-03-09 07:16

import apps.media.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.media.models.upload_to, verbose_name="文件"
                    ),
                ),
                ("filename", models.CharField(max_length=200, verbose_name="文件名")),
                ("file_type", models.CharField(max_length=50, verbose_name="文件类型")),
                (
                    "file_size",
                    models.PositiveIntegerField(verbose_name="文件大小(字节)"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="上传时间"),
                ),
            ],
            options={
                "verbose_name": "媒体文件",
                "verbose_name_plural": "媒体文件",
                "db_table": "media",
                "ordering": ["-created_at"],
            },
        ),
    ]
