# Generated by Django 5.2.12 on 2026-03-09 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="media",
            name="file_hash",
            field=models.CharField(blank=True, max_length=32, verbose_name="文件MD5"),
        ),
    ]
