# Generated by Django 5.2.12 on 2026-03-10 06:06

import apps.media.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0003_media_file_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="media",
            name="thumbnails",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.media.models.thumbnails_upload_to,
                verbose_name="缩略图",
            ),
        ),
        migrations.AddField(
            model_name="media",
            name="thumbnails_vtt",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=apps.media.models.thumbnails_upload_to,
                verbose_name="缩略图VTT",
            ),
        ),
    ]
