# Generated by Django 5.2.12 on 2026-03-10 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0004_media_thumbnails_media_thumbnails_vtt"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="media",
            name="thumbnails_vtt",
        ),
        migrations.AddField(
            model_name="media",
            name="thumbnails_count",
            field=models.PositiveIntegerField(default=0, verbose_name="缩略图数量"),
        ),
    ]
