# Generated by Django 5.2.12 on 2026-03-10 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0005_remove_media_thumbnails_vtt_media_thumbnails_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="media",
            name="thumbnail_status",
            field=models.CharField(
                choices=[
                    ("pending", "等待中"),
                    ("processing", "处理中"),
                    ("completed", "已完成"),
                    ("failed", "失败"),
                ],
                default="pending",
                max_length=20,
                verbose_name="缩略图状态",
            ),
        ),
    ]
