# Generated by Django 5.2.12 on 2026-03-13 08:06

import apps.media.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0006_media_thumbnail_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="media",
            name="reference",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="references",
                to="media.media",
                verbose_name="引用文件",
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=apps.media.models.upload_to,
                verbose_name="文件",
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="file_hash",
            field=models.CharField(blank=True, max_length=32, verbose_name="文件 MD5"),
        ),
        migrations.AlterField(
            model_name="media",
            name="file_size",
            field=models.PositiveIntegerField(verbose_name="文件大小 (字节)"),
        ),
    ]
