# Generated by Django 5.2.12 on 2026-03-28 11:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0007_media_reference_alter_media_file_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="media",
            name="reference_count",
            field=models.PositiveIntegerField(
                default=0, editable=False, verbose_name="引用计数"
            ),
        ),
        migrations.AddIndex(
            model_name="media",
            index=models.Index(fields=["file_hash"], name="media_file_hash_idx"),
        ),
        migrations.AddIndex(
            model_name="media",
            index=models.Index(
                fields=["uploader", "-created_at"], name="media_uploader_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="media",
            index=models.Index(fields=["file_type"], name="media_file_type_idx"),
        ),
    ]
