# Generated by Django 5.2.12 on 2026-03-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0008_media_reference_count_media_media_file_hash_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="media",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="media",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
    ]
