# Generated by Django 5.2.12 on 2026-05-03 09:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0009_media_updated_at_alter_media_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['thumbnail_status'], name='media_thumbnail_status_idx'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['reference_count'], name='media_reference_count_idx'),
        ),
    ]
