# Generated by Django 5.2.12 on 2026-03-09 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=30, unique=True, verbose_name="URL别名"
            ),
        ),
    ]
