# Generated by Django 5.2.12 on 2026-03-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0002_alter_tag_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=30, unique=True, verbose_name="URL 别名"
            ),
        ),
    ]
