# Generated by Django 5.2.12 on 2026-05-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_tag_updated_at_alter_tag_slug'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['-created_at'], name='tag_created_idx'),
        ),
    ]
