# Generated by Django 5.2.12 on 2026-03-28 11:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0005_comment_reply_to"),
        ("contents", "0003_content_content_status_created_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AddField(
            model_name="commentlike",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["article", "-created_at"], name="comment_article_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["user", "-created_at"], name="comment_user_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["is_approved", "-created_at"],
                name="comment_approved_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(fields=["parent"], name="comment_parent_idx"),
        ),
        migrations.AddIndex(
            model_name="commentlike",
            index=models.Index(fields=["user"], name="comment_like_user_idx"),
        ),
    ]
