# Generated by Django 5.2.12 on 2026-05-03 09:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_comment_updated_at_commentlike_updated_at_and_more'),
        ('contents', '0004_content_content_cat_stat_created_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['article', 'is_approved', '-created_at'], name='comment_art_appr_created_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['user', 'is_approved'], name='comment_user_appr_idx'),
        ),
        migrations.AddIndex(
            model_name='commentlike',
            index=models.Index(fields=['comment'], name='comment_like_comment_idx'),
        ),
        migrations.AddIndex(
            model_name='commentlike',
            index=models.Index(fields=['user', 'comment'], name='comment_like_user_comment_idx'),
        ),
    ]
